vich_uploader:
    db_driver: orm

    mappings:
        products_images:
            uri_prefix: /assets/uploads/products
            upload_destination: '%kernel.project_dir%/public/assets/uploads/products'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_remove: true
            delete_on_update: true
